#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter 'sh /afs/cern.ch/work/d/devdatta/CMSREL/CMSSW_5_3_9_BpbH/src/BprimebHAnalysis/BprimeTobH/test/bprimetobh_cfg.sh'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
